/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.tib.resisteur;

/**
 *
 * @author Tib
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox23 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resisteur Coleur code calculateur");
        setMinimumSize(new java.awt.Dimension(1301, 801));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Resisteur Coleur code calculateur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1260, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Tolerance");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 40));

        jCheckBox1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox1.setText("None");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox1.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Black");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox2.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox2.setPreferredSize(new java.awt.Dimension(130, 30));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jCheckBox3.setBackground(new java.awt.Color(161, 56, 56));
        jCheckBox3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox3.setText("Brown");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox3.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox3.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox3.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jCheckBox4.setBackground(new java.awt.Color(255, 0, 0));
        jCheckBox4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox4.setText("Red");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox4.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox4.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox4.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 102, 0));
        jCheckBox5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox5.setText("Orange");
        jCheckBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox5.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox5.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox5.setPreferredSize(new java.awt.Dimension(130, 30));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 0));
        jCheckBox6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox6.setText("Yellow");
        jCheckBox6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox6.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox6.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox6.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jCheckBox7.setBackground(new java.awt.Color(51, 255, 0));
        jCheckBox7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox7.setText("Green");
        jCheckBox7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox7.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox7.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox7.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jCheckBox8.setBackground(new java.awt.Color(0, 51, 204));
        jCheckBox8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox8.setText("Blue");
        jCheckBox8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox8.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox8.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox8.setPreferredSize(new java.awt.Dimension(130, 30));
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jCheckBox9.setBackground(new java.awt.Color(153, 0, 255));
        jCheckBox9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox9.setText("Violet");
        jCheckBox9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox9.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox9.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox9.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jCheckBox10.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBox10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox10.setText("Gray");
        jCheckBox10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox10.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox10.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox10.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jCheckBox11.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox11.setText("White");
        jCheckBox11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox11.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox11.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox11.setPreferredSize(new java.awt.Dimension(130, 30));
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jCheckBox12.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox12.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox12.setText("Gold");
        jCheckBox12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox12.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox12.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox12.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jCheckBox13.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText("1");
        jCheckBox13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox13.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox13.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox13.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jCheckBox14.setBackground(new java.awt.Color(161, 56, 56));
        jCheckBox14.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox14.setText("10");
        jCheckBox14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox14.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox14.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox14.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jCheckBox15.setBackground(new java.awt.Color(255, 0, 0));
        jCheckBox15.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox15.setText("10²");
        jCheckBox15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox15.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox15.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox15.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        jCheckBox16.setBackground(new java.awt.Color(255, 102, 0));
        jCheckBox16.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox16.setText("10 ");
        jCheckBox16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox16.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox16.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox16.setPreferredSize(new java.awt.Dimension(130, 30));
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jCheckBox17.setBackground(new java.awt.Color(255, 255, 0));
        jCheckBox17.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox17.setText("10000");
        jCheckBox17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox17.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox17.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox17.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jCheckBox18.setBackground(new java.awt.Color(51, 255, 0));
        jCheckBox18.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox18.setText("100000");
        jCheckBox18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox18.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox18.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox18.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jCheckBox19.setBackground(new java.awt.Color(0, 51, 204));
        jCheckBox19.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox19.setText("1000000");
        jCheckBox19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox19.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox19.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox19.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jCheckBox20.setBackground(new java.awt.Color(153, 0, 255));
        jCheckBox20.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox20.setText("10000000");
        jCheckBox20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox20.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox20.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox20.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jCheckBox21.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBox21.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox21.setText("100000000");
        jCheckBox21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox21.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox21.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox21.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jCheckBox22.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox22.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox22.setText("1000000000");
        jCheckBox22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox22.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox22.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox22.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Coleur");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 40));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Multiplier");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 40));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+5));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel5.setOpaque(true);
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 120, 30));

        jLabel6.setBackground(java.awt.Color.black);
        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, jLabel6.getFont().getSize()+5));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel6.setOpaque(true);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, 30));

        jLabel7.setBackground(new java.awt.Color(161, 56, 56));
        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD, jLabel7.getFont().getSize()+5));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setOpaque(true);
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 30));

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD, jLabel8.getFont().getSize()+5));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("2");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 30));

        jLabel9.setBackground(new java.awt.Color(255, 102, 0));
        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD, jLabel9.getFont().getSize()+5));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setOpaque(true);
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 0));
        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD, jLabel10.getFont().getSize()+5));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("4");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 30));

        jLabel11.setBackground(new java.awt.Color(51, 255, 0));
        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, jLabel11.getFont().getSize()+5));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("5");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setOpaque(true);
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, 30));

        jLabel12.setBackground(new java.awt.Color(0, 51, 204));
        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getStyle() | java.awt.Font.BOLD, jLabel12.getFont().getSize()+5));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("6");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setOpaque(true);
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 120, 30));

        jLabel13.setBackground(new java.awt.Color(153, 0, 255));
        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getStyle() | java.awt.Font.BOLD, jLabel13.getFont().getSize()+5));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("7");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setOpaque(true);
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 30));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(jLabel14.getFont().deriveFont(jLabel14.getFont().getStyle() | java.awt.Font.BOLD, jLabel14.getFont().getSize()+5));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("8");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel14.setOpaque(true);
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 120, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(jLabel15.getFont().deriveFont(jLabel15.getFont().getStyle() | java.awt.Font.BOLD, jLabel15.getFont().getSize()+5));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("9");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel15.setOpaque(true);
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 30));

        jLabel16.setBackground(new java.awt.Color(255, 204, 0));
        jLabel16.setFont(jLabel16.getFont().deriveFont(jLabel16.getFont().getStyle() | java.awt.Font.BOLD, jLabel16.getFont().getSize()+5));
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel16.setOpaque(true);
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 120, 30));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getStyle() | java.awt.Font.BOLD, jLabel17.getFont().getSize()+5));
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel17.setOpaque(true);
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 120, 30));

        jLabel18.setBackground(new java.awt.Color(255, 204, 0));
        jLabel18.setFont(jLabel18.getFont().deriveFont(jLabel18.getFont().getStyle() | java.awt.Font.BOLD, jLabel18.getFont().getSize()+5));
        jLabel18.setText("0.1");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel18.setOpaque(true);
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 120, 30));

        jCheckBox23.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox23.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jCheckBox23.setText("Silver");
        jCheckBox23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCheckBox23.setMaximumSize(new java.awt.Dimension(150, 30));
        jCheckBox23.setMinimumSize(new java.awt.Dimension(150, 30));
        jCheckBox23.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel5.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(jLabel19.getFont().deriveFont(jLabel19.getFont().getStyle() | java.awt.Font.BOLD, jLabel19.getFont().getSize()+5));
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel19.setOpaque(true);
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 120, 30));

        jLabel20.setBackground(java.awt.Color.black);
        jLabel20.setFont(jLabel20.getFont().deriveFont(jLabel20.getFont().getStyle() | java.awt.Font.BOLD, jLabel20.getFont().getSize()+5));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("0");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel20.setOpaque(true);
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 120, 30));

        jLabel21.setBackground(new java.awt.Color(161, 56, 56));
        jLabel21.setFont(jLabel21.getFont().deriveFont(jLabel21.getFont().getStyle() | java.awt.Font.BOLD, jLabel21.getFont().getSize()+5));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel21.setOpaque(true);
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 120, 30));

        jLabel22.setBackground(new java.awt.Color(255, 0, 0));
        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getStyle() | java.awt.Font.BOLD, jLabel22.getFont().getSize()+5));
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel22.setOpaque(true);
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 30));

        jLabel23.setBackground(new java.awt.Color(255, 102, 0));
        jLabel23.setFont(jLabel23.getFont().deriveFont(jLabel23.getFont().getStyle() | java.awt.Font.BOLD, jLabel23.getFont().getSize()+5));
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel23.setOpaque(true);
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 120, 30));

        jLabel24.setBackground(new java.awt.Color(255, 255, 0));
        jLabel24.setFont(jLabel24.getFont().deriveFont(jLabel24.getFont().getStyle() | java.awt.Font.BOLD, jLabel24.getFont().getSize()+5));
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel24.setOpaque(true);
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 120, 30));

        jLabel25.setBackground(new java.awt.Color(51, 255, 0));
        jLabel25.setFont(jLabel25.getFont().deriveFont(jLabel25.getFont().getStyle() | java.awt.Font.BOLD, jLabel25.getFont().getSize()+5));
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel25.setOpaque(true);
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 120, 30));

        jLabel26.setBackground(new java.awt.Color(0, 51, 204));
        jLabel26.setFont(jLabel26.getFont().deriveFont(jLabel26.getFont().getStyle() | java.awt.Font.BOLD, jLabel26.getFont().getSize()+5));
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel26.setOpaque(true);
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 120, 30));

        jLabel27.setBackground(new java.awt.Color(153, 0, 255));
        jLabel27.setFont(jLabel27.getFont().deriveFont(jLabel27.getFont().getStyle() | java.awt.Font.BOLD, jLabel27.getFont().getSize()+5));
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel27.setOpaque(true);
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 120, 30));

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(jLabel28.getFont().deriveFont(jLabel28.getFont().getStyle() | java.awt.Font.BOLD, jLabel28.getFont().getSize()+5));
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel28.setOpaque(true);
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 120, 30));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(jLabel29.getFont().deriveFont(jLabel29.getFont().getStyle() | java.awt.Font.BOLD, jLabel29.getFont().getSize()+5));
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel29.setOpaque(true);
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 120, 30));

        jLabel30.setBackground(new java.awt.Color(255, 204, 0));
        jLabel30.setFont(jLabel30.getFont().deriveFont(jLabel30.getFont().getStyle() | java.awt.Font.BOLD, jLabel30.getFont().getSize()+5));
        jLabel30.setText("5%");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel30.setOpaque(true);
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 120, 30));

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(jLabel31.getFont().deriveFont(jLabel31.getFont().getStyle() | java.awt.Font.BOLD, jLabel31.getFont().getSize()+5));
        jLabel31.setText("10%");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel31.setOpaque(true);
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 120, 30));

        jLabel32.setFont(jLabel32.getFont().deriveFont(jLabel32.getFont().getStyle() | java.awt.Font.BOLD, jLabel32.getFont().getSize()+5));
        jLabel32.setText("20%");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel32.setOpaque(true);
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 120, 30));

        jLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jLabel33.setFont(jLabel33.getFont().deriveFont(jLabel33.getFont().getStyle() | java.awt.Font.BOLD, jLabel33.getFont().getSize()+5));
        jLabel33.setText("0.01");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel33.setOpaque(true);
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 120, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 600, 490));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 600, 470));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1260, 520));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1256, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 1260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
